version: '3'
services:
  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mail
      PGADMIN_DEFAULT_PASSWORD: 2312
    ports:
      - "80:80"
  db:
    build: ./db_dumps/.
    image: postgres-clear
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: password
    ports:
      - "8090:5432"
  newman:
    build: ./testing_env/.
    image: postman_checks
    container_name: newman
    volumes:
      - ${PWD}/testing_env:/etc/newman
    command: 
      run -g /etc/newman/newman_globals.json /etc/newman/API_tests.json
      --reporters cli,html
      --reporter-html-export Test_output.html
      --reporter-html-template /etc/newman/template.hbs
    depends_on:
      - app
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    environment:
      VERBOSE: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db